language: generic 
sudo: required
services:
    -docker

before_install:
    - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true react-test npm run test

after_success:
    - docker build -t eliranazulay/multi-client ./client
    - docker build -t eliranazulay/multi-nginx ./nginx
    - docker build -t eliranazulay/multi-server ./server
    - docker build -t eliranazulay/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$docker_password" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to docker hub
    - docker push eliranazulay/multi-client
    - docker push eliranazulay/multi-nginx
    - docker push eliranazulay/multi-server
    - docker push eliranazulay/multi-worker



deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker"
    env: "Multi-Docker"
    bucket_name: "elasticbeanstalk-eu-west-2-821285884288"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY

        